# - list of names of dynamically loaded trackers
trackers : [
  "MpcTracker",
  "LineTracker",
  "LandoffTracker",
  "JoyTracker",
  "MatlabTracker",
  "NullTracker",
  "JoyBumperTracker",
]

# - list of names of dynamically loaded controllers
controllers : [
  "MpcController",
  "So3Controller",
  "NsfController",
  "AttitudeController",
  "AccelerationController",
  "FailsafeController",
  "EmergancyController",
]

safety:

  min_thrust_null_tracker: 0.15 # [] minimum thrust when not flying

  # after not receiving odometry for more than this, the failsafe landing will trigger
  odometry_max_missing_time: 2.0 # [s]
