MpcController:
  address: "mrs_controllers/MpcController"
  eland_threshold: 3.5
  failsafe_threshold: 5.0

FailsafeController:
  address: "mrs_controllers/FailsafeController"
  eland_threshold: 0.0
  failsafe_threshold: 0.0
