MpcController:
  address: "mrs_controllers/MpcController"
  eland_threshold: 0.0
  failsafe_threshold: 10.0

FailsafeController:
  address: "mrs_controllers/FailsafeController"
  eland_threshold: 0.0
  failsafe_threshold: 0.0
