takeoff:

  during_takeoff:
    tracker: "LandoffTracker"
    controller: "MpcController"

  after_takeoff:
    tracker: "MpcTracker"
    controller: "So3Controller"

    pirouette: false

  takeoff_height: 2.0

landing:

  disarm: false
