supersoft:

  horizontal:
    kp: 6.0
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 1.0
    kib_lim: 10.0

    kiw: 1.0
    kiw_lim: 10.0

  vertical:
    kp: 15.0
    kv: 8.0
    ka: 1.0

    attitude:
      kq: 10.0
      kw: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 4.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

soft:

  horizontal:
    kp: 8.0
    kv: 6.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 0.1
    kib_lim: 10.0

    kiw: 0.1
    kiw_lim: 10.0

  vertical:
    kp: 15.0
    kv: 8.0
    ka: 1.0

    attitude:
      kq: 10.0
      kw: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 4.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

tight:

  horizontal:
    kp: 12.0
    kv: 8.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 0.1
    kib_lim: 10.0

    kiw: 0.1
    kiw_lim: 10.0

  vertical:
    kp: 15.0
    kv: 8.0
    ka: 1.0

    attitude:
      kq: 10.0
      kw: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 4.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
