supersoft:

  horizontal:
    kp: 5.0
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 0.3
    kib_lim: 10.0

    kiw: 0.3
    kiw_lim: 10.0

  vertical:
    kp: 5.0
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.1

  weight_estimator:
    km: 1.0
    km_lim: 6.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

soft:

  horizontal:
    kp: 10.0
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 0.7
    kib_lim: 10.0

    kiw: 0.7
    kiw_lim: 10.0

  vertical:
    kp: 8.0
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.1

  weight_estimator:
    km: 1.0
    km_lim: 6.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

tight:

  horizontal:
    kp: 14.0
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 1.0
    kib_lim: 10.0

    kiw: 1.0
    kiw_lim: 10.0

  vertical:
    kp: 10.0
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.1

  weight_estimator:
    km: 1.0
    km_lim: 6.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
