slow:

  horizontal:
    speed: 1.5
    acceleration: 1.0
    jerk: 1.0
    snap: 2.0

  vertical:

    ascending:
      speed: 0.5
      acceleration: 1.0
      jerk: 1.0
      snap: 1.0

    descending:
      speed: 0.5
      acceleration: 1.0
      jerk: 1.0
      snap: 1.0

  yaw:
    speed: 0.15
    acceleration: 0.2
    jerk: 1.0
    snap: 1.0
