slow:

  horizontal:
    speed: 1.5
    acceleration: 1.0
    jerk: 3.0
    snap: 5.0

  vertical:

    ascending:
      speed: 1.0
      acceleration: 1.0
      jerk: 2.0
      snap: 5.0

    descending:
      speed: 1.0
      acceleration: 1.0
      jerk: 2.0
      snap: 5.0

  yaw:
    speed: 0.2
    acceleration: 0.2
    jerk: 3.0
    snap: 5.0
