MpcTracker:
  address: "mrs_trackers/MpcTracker"

LandoffTracker:
  address: "mrs_trackers/LandoffTracker"

LineTracker:
  address: "mrs_trackers/LineTracker"

WallTracker:
  address: "mrs_trackers/WallTracker"

JoyTracker:
  address: "mrs_trackers/JoyTracker"

JoyBumperTracker:
  address: "mrs_trackers/JoyBumperTracker"

MatlabTracker:
  address: "mrs_trackers/MatlabTracker"

NullTracker:
  address: "mrs_uav_manager/NullTracker"
